# fly.toml app configuration file generated for ucdp-project on 2024-09-29T19:05:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ucdp-project'
primary_region = 'cdg'

[deploy]
release_command = "gunicorn -b 0.0.0.0:8080 Visualization:app"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
